server:
  port: 8086
spring:
  application:
    name: sms-service
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: ${spring.application.name}
    send-message-timeout: 20000

ly:
  sms:
    accessKeyId: LTAIUVK6tAM6xxYm
    accessKeySecret: L5Y0Lg6r2cAHgm6uVAdkLe5RdzWpRn
    signName: 顺义leyou项目 # 签名名称
    verifyCodeTemplate: SMS_169636334 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou # 区域id