server:
  port: 10010
spring:
  application:
    name: ly-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka   #指定eureka的服务器地址
    registry-fetch-interval-seconds: 5             #设置5秒抓取服务
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
ribbon:
  ConnectTimeout: 500 # ribbon链接超时时长
  ReadTimeout: 2000 # ribbon读取超时时长
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 1 # 切换服务重试次数
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试，只对get请求重试
zuul:
  prefix: /api     #网关请求前缀加 /api
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**   路由规则
    upload-service: /upload/** #图片上传微服务
    search-service: /search/** #搜索微服务
ly:
  cors:
    allowedOrigins:
    - http://manage.leyou.com
    - http://www.leyou.com
    allowedCredentials: true
    allowedHeaders:
    - "*"
    allowedMethods:
    - GET
    - POST
    - DELETE
    - PUT
    - OPTIONS
    - HEAD
    maxAge: 3600
    filterPath: "/**"
 zuul:
    prefix: /api # 添加路由前缀
    routes:
      item-service: /item/**  # 将商品微服务映射到/item/**
      upload-service: /upload/** #上传文件的映射
      search-service: /search/** #搜索微服务
      user-service: /user/** #用户微服务